config/routes.rb
Rails.application.routes.draw do

  get "questions/last" => "questions#last_question", :as => "questions/last"
  resources :import do
    collection do
      post :import
    end
  end
  resources :questions
  resources :reports do
    collection do
      get :export
    end
  end

  resources :jobs

  resources :diseases

  resources :users
  resources :pcr_forms do
    collection do
      get :export
      get :markers
    end
  end

  resources :locations do
    collection do
      get 'sub_locations'
      get 'all_provinces'
      get 'parent_locations_with_kind'
      get 'parent_location_with_child_id'
    end
  end

  root 'sessions#new'
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  resource :sessions

end

app/controllers/pcr_forms_controller.rb
require "csv"
class PcrFormsController < ApplicationController
  load_and_authorize_resource :except => [:create, :update], param_method: :pcrForm_params
  before_action :set_pcrForm, only: [:show, :edit, :update, :destroy]
  def index
    @pcrForms = pcrForm_scope.paginate(page: params[:page], per_page: 15)
    @k13PositiveCase = @pcrForms.where(:k13 => ['C580Y']).count
    @totalRecord = pcrForm_scope.count
    @currentRecord = @pcrForms.count
    @redIndicator = @pcrForms.where(:k13 => ['C580Y', 'R539T', 'Y493H', 'I543T']).count
    @blueIndicator = @pcrForms.where.not(:k13 => ['C580Y', 'R539T', 'Y493H', 'I543T']).count
    @greenIndicator = @pcrForms.where(pcr_malaria: 'Positive').where.not(:k13 => ['C580Y', 'R539T', 'Y493H', 'I543T']).count
  end

  def markers
    render json: pcrForm_scope
  end

  def new
  	@pcrForm = PcrForm.new
  end

  def create
    @pcrForm = PcrForm.new(pcrForm_params)
    respond_to do |format|
      if @pcrForm.save
        format.html { redirect_to pcr_forms_path, notice: 'PcrForm was successfully created.' }
        format.json { render :show, status: :created, location: @pcrForm }
      else
        format.html { render :new }
        format.json { render json: @pcrForm.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update
    page = params[:page] != "" ? params[:page] : 1
    respond_to do |format|
      if @pcrForm.update(pcrForm_params)
        format.html { redirect_to pcr_forms_path(page: page), notice: 'PcrForm was successfully updated.' }
        format.json { render :index, status: :ok, location: @pcrForm }
      else
        format.html { render :edit }
        format.json { render json: @pcrForm.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pcrForm.destroy
    respond_to do |format|
      format.html { redirect_to pcr_forms_url, notice: 'PcrForm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def export
    if params[:fromDate] != "" && params[:endDate] != ""
      @pcrForms = pcrForm_scope.where(:date => params[:fromDate]..params[:toDate])
    else
      @pcrForms = pcrForm_scope
    end

    respond_to do |format|
      format.csv { send_data @pcrForms.to_csv(current_user),:type => 'text/csv; charset=iso-8859-1; header=present',:disposition => "attachment; filename = export.csv" }
      format.xls do
        response.headers['Content-Disposition'] = 'attachment; filename="export.xls"'
        render "export.xls.erb"
      end
    end
  end

  # def sample_list

  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pcrForm
      @pcrForm = PcrForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pcrForm_params
      params.require(:pcr_form).permit(:date_of_case_received, :date_of_k13_result, :sample_id, :pcr_malaria, :tm, :rt_pcr_species, :k13, :final_k13_result, :date_final_k13_result, :date, :client_name, :sex, :age, :phone_number, :location, :village, :commune, :hc, :od, :province, :latitude, :longitude)
    end

    def pcrForm_scope
      pcr_forms = PcrForm.order("date_of_case_received desc")
      pcr_forms = pcr_forms.where('lower(sample_id) = ?', params[:sample_id].downcase) if params[:sample_id].present? && params[:sample_id] != ""
      pcr_forms = pcr_forms.where(k13: params[:k13]) if params[:k13] && params[:k13] != "All"
      pcr_forms
    end

end

app/views/pcr_forms/_default_form.html.erb
<div class="control-group">
  <%= f.label :date_of_case_received %>
  <div class='controls'>
    <%= f.text_field 'date_of_case_received', :class => 'datepicker' %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'PCR Screening' %>
  <div class='controls'>
    <%= f.select('pcr_malaria', PcrForm::PCR_MALARIA, include_blank: "Select PCR Malaria") %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Ct' %>
  <div class='controls'>
    <%= f.text_field 'tm' %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'PCR Species' %>
  <div class='controls'>
    <%= f.select('rt_pcr_species', PcrForm::RT, include_blank: "Select RT_PCR Species") %>
    <%#= f.text_field 'rt_pcr_species' %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Pre-k13 Result' %>
  <div class='controls'>
    <%= f.text_field 'k13' %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Final k13 Result' %>
  <div class='controls'>
    <%= f.text_field 'final_k13_result' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :date_of_k13_result %>
  <div class='controls'>
    <%= f.text_field 'date_of_k13_result', :class => 'datepicker' %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Date of Final-K13 Result' %>
  <div class='controls'>
    <%= f.text_field 'date_final_k13_result', :class => 'datepicker' %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Date of RDT' %>
  <div class='controls'>
    <%= f.text_field 'date', :class => 'datepicker' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :client_name %>
  <div class='controls'>
    <%= f.text_field 'client_name' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :sex %>
  <div class='controls'>
    <%= f.radio_button(:sex, "Female") %>
    <span>Female</span>&nbsp;&nbsp;&nbsp;
    <%= f.radio_button(:sex, "Male") %>
    <span>Male</span>
  </div>
</div>

<div class="control-group">
  <%= f.label :age %>
  <div class='controls'>
    <%= f.number_field 'age' %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :phone_number %>
  <div class='controls'>
    <%= f.number_field 'phone_number' %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :Village %>
  <div class='controls'>
    <%= f.text_field 'village' %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :commune %>
  <div class='controls'>
    <%= f.text_field 'commune' %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :health_center %>
  <div class='controls'>
    <%= f.text_field 'hc' %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :operational_district %>
  <div class='controls'>
    <%= f.text_field 'od' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :province %>
  <div class='controls'>
    <%= f.text_field 'province' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :latitude %>
  <div class='controls'>
    <%= f.text_field 'latitude' %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :longitude %>
  <div class='controls'>
    <%= f.text_field 'longitude' %>
  </div>
</div>

app/views/pcr_forms/_first_entry_form.html.erb
<div class="control-group">
  <%= f.label :date_of_case_received %>
  <div class='controls'>
    <%= f.text_field 'date_of_case_received', :class => 'datepicker', disabled: true %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'PCR Screening' %>
  <div class='controls'>
    <%= f.text_field 'pcr_malaria', disabled: true %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Ct' %>
  <div class='controls'>
    <%= f.text_field 'tm', disabled: true %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'PCR Species' %>
  <div class='controls'>
    <%= f.text_field 'rt_pcr_species', disabled: true %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Pre-k13 Result' %>
  <div class='controls'>
    <%= f.text_field 'k13', disabled: true %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Final k13 Result' %>
  <div class='controls'>
    <%= f.text_field 'final_k13_result', disabled: true %>
  </div>
</div>

<div class="control-group">
  <%= f.label :date_of_k13_result %>
  <div class='controls'>
    <%= f.text_field 'date_of_k13_result', :class => 'datepicker', disabled: true %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Date of Final-K13 Result' %>
  <div class='controls'>
    <%= f.text_field 'date_final_k13_result', :class => 'datepicker', disabled: true %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Date of RDT' %>
  <div class='controls'>
    <%= f.text_field 'date', :class => 'datepicker' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :client_name %>
  <div class='controls'>
    <%= f.text_field 'client_name' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :sex %>
  <div class='controls'>
    <%= f.radio_button(:sex, "Female") %>
    <span>Female</span>&nbsp;&nbsp;&nbsp;
    <%= f.radio_button(:sex, "Male") %>
    <span>Male</span>
  </div>
</div>

<div class="control-group">
  <%= f.label :age %>
  <div class='controls'>
    <%= f.number_field 'age' %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :phone_number %>
  <div class='controls'>
    <%= f.number_field 'phone_number' %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :Village %>
  <div class='controls'>
    <%= f.text_field 'village' %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :commune %>
  <div class='controls'>
    <%= f.text_field 'commune' %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :health_center %>
  <div class='controls'>
    <%= f.text_field 'hc' %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :operational_district %>
  <div class='controls'>
    <%= f.text_field 'od' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :province %>
  <div class='controls'>
    <%= f.text_field 'province' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :latitude %>
  <div class='controls'>
    <%= f.text_field 'latitude' %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :longitude %>
  <div class='controls'>
    <%= f.text_field 'longitude' %>
  </div>
</div>

app/views/pcr_forms/_form.html.erb
<%= form_for(@pcrForm, :html => { :class => 'form-horizontal ' }) do |f| %>

  <% if @pcrForm.errors.any? %>
    <div class="alert alert-error">
      <p><%= pluralize(@pcrForm.errors.count, "error") %> prohibited this data from being saved:</p>

      <ul>
      <% @pcrForm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>

  <%= hidden_field_tag 'page', params[:page] %>
  <div class="control-group">
    <%= f.label 'Sample ID' %>
    <div class='controls'>
      <%= f.text_field 'sample_id' %>
    </div>
  </div>

  <% if current_user.first_entry? %>
    <%= render 'first_entry_form', f: f %>
  <% elsif current_user.second_entry? %>
    <%= render 'second_entry_form', f: f %>
  <% else %>
    <%= render 'default_form', f: f %>
  <% end -%>

  <div >
    <div class="controls">
      <%= f.submit 'Submit', :class => 'btn btn-default' %>
    </div>
  </div>

<% end -%>


<script type="text/javascript">
  $(document).ready(function(){

    $('.datepicker').datepicker({
        format: 'yyyy-mm-dd',
        autoClose: true
    });

  });


</script>

app/views/pcr_forms/_second_entry_form.html.erb
<div class="control-group">
  <%= f.label :date_of_case_received %>
  <div class='controls'>
    <%= f.text_field 'date_of_case_received', :class => 'datepicker' %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'PCR Screening' %>
  <div class='controls'>
    <%= f.select('pcr_malaria', PcrForm::PCR_MALARIA, include_blank: "Select PCR Malaria") %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Ct' %>
  <div class='controls'>
    <%= f.text_field 'tm' %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'PCR Species' %>
  <div class='controls'>
    <%= f.select('rt_pcr_species', PcrForm::RT, include_blank: "Select RT_PCR Species") %>
    <%#= f.text_field 'rt_pcr_species' %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Pre-k13 Result' %>
  <div class='controls'>
    <%= f.text_field 'k13' %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Final k13 Result' %>
  <div class='controls'>
    <%= f.text_field 'final_k13_result' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :date_of_k13_result %>
  <div class='controls'>
    <%= f.text_field 'date_of_k13_result', :class => 'datepicker' %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Date of Final-K13 Result' %>
  <div class='controls'>
    <%= f.text_field 'date_final_k13_result', :class => 'datepicker' %>
  </div>
</div>

<div class="control-group">
  <%= f.label 'Date of RDT' %>
  <div class='controls'>
    <%= f.text_field 'date', :class => 'datepicker', disabled: true %>
  </div>
</div>

<div class="control-group">
  <%= f.label :client_name %>
  <div class='controls'>
    <%= f.text_field 'client_name', disabled: true %>
  </div>
</div>

<div class="control-group">
  <%= f.label :sex %>
  <div class='controls'>
    <%= f.radio_button(:sex, "Female", disabled: true) %>
    <span>Female</span>&nbsp;&nbsp;&nbsp;
    <%= f.radio_button(:sex, "Male", disabled: true) %>
    <span>Male</span>
  </div>
</div>

<div class="control-group">
  <%= f.label :age %>
  <div class='controls'>
    <%= f.number_field 'age', disabled: true %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :phone_number %>
  <div class='controls'>
    <%= f.number_field 'phone_number', disabled: true %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :Village %>
  <div class='controls'>
    <%= f.text_field 'village', disabled: true %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :commune %>
  <div class='controls'>
    <%= f.text_field 'commune', disabled: true %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :health_center %>
  <div class='controls'>
    <%= f.text_field 'hc', disabled: true %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :operational_district %>
  <div class='controls'>
    <%= f.text_field 'od', disabled: true %>
  </div>
</div>

<div class="control-group">
  <%= f.label :province %>
  <div class='controls'>
    <%= f.text_field 'province', disabled: true %>
  </div>
</div>

<div class="control-group">
  <%= f.label :latitude %>
  <div class='controls'>
    <%= f.text_field 'latitude', disabled: true %>
  </div>
</div>

 <div class="control-group">
  <%= f.label :longitude %>
  <div class='controls'>
    <%= f.text_field 'longitude', disabled: true %>
  </div>
</div>

app/views/pcr_forms/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit PCR Survey
  </div>
  <div class="panel-body">
	<%= render 'form' %>
  </div>
</div>

app/views/pcr_forms/export.xls.erb
<?xml version="1.0" encoding="UTF-8"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Sample-ID</Data></Cell>
        <Cell><Data ss:Type="String">DBS_Received Date</Data></Cell>
        <Cell><Data ss:Type="String">Date of case received</Data></Cell>
        <Cell><Data ss:Type="String">PCR Screening</Data></Cell>
        <Cell><Data ss:Type="String">Ct</Data></Cell>
        <Cell><Data ss:Type="String">PCR Species</Data></Cell>
        <Cell><Data ss:Type="String">Pre-K13 Result</Data></Cell>
        <Cell><Data ss:Type="String">Final-K13 Result</Data></Cell>
        <Cell><Data ss:Type="String">Date of K13 result</Data></Cell>
        <Cell><Data ss:Type="String">Date of Final K13 result</Data></Cell>
        <Cell><Data ss:Type="String">Date of RDT</Data></Cell>
        <Cell><Data ss:Type="String">Client Name</Data></Cell>
        <Cell><Data ss:Type="String">Sex</Data></Cell>
        <Cell><Data ss:Type="String">Age</Data></Cell>
        <Cell><Data ss:Type="String">Phone number</Data></Cell>
        <Cell><Data ss:Type="String">Village</Data></Cell>
        <Cell><Data ss:Type="String">Commune</Data></Cell>
        <Cell><Data ss:Type="String">Health Center</Data></Cell>
        <Cell><Data ss:Type="String">Operational District</Data></Cell>
        <Cell><Data ss:Type="String">Province</Data></Cell>
        <Cell><Data ss:Type="String">Latitude</Data></Cell>
        <Cell><Data ss:Type="String">Longitude</Data></Cell>
      </Row>
    <% @pcrForms.each do |pcrForm| %>
      <Row>
        <Cell><Data ss:Type="String"><%= pcrForm.sample_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.dbs_received_date.to_date if !pcrForm.dbs_received_date.nil? %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.date_of_case_received.to_date if !pcrForm.date_of_case_received.nil? %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.pcr_malaria %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.tm %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.rt_pcr_species %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.k13 %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.final_k13_result %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.date_of_k13_result.to_date if !pcrForm.date_of_k13_result.nil? %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.date_final_k13_result.to_date if !pcrForm.date_final_k13_result.nil? %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.date %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.client_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.sex %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.age %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.phone_number %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.village %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.commune %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.hc %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.od %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.province %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.latitude %></Data></Cell>
        <Cell><Data ss:Type="String"><%= pcrForm.longitude %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/pcr_forms/index.html.erb
<% if flash[:alert] %>
  <div class="alert alert-error">
  <%= flash[:alert] %>
  </div>
<% end -%>

<div class="panel panel-default">
  <div class="panel-heading">
    Listing reports
    <div class="pull-right"><a href="#" class="view"><img src="/assets/table.png" title="Table view" id="iconTable" style="display:none"><img id="iconMap" title="Map view" src="/assets/map.png"></a></div>
  </div>
  <div class="panel-body">
    <div  id="table">
      <% if can? :create, PcrForm.new %>
        <%= link_to 'New PCR Form', new_pcr_form_path, :class => 'btn btn-small' %>
      <% end -%>
      <br/>
      <!-- <br/> -->
      <%#= form_tag pcr_forms_path, :method => 'get', class: 'form-inline' do %>
        <%#= select_tag 'k13', options_for_select(["All", "C580Y", "F583L*", "I543T", "NA", "NI", "PCR negative", "R539T", "WT", "Y493H", "Y616Y*"]), :prompt => "Please select" %>
        <%#= submit_tag 'search', class: 'btn btn-primary'%>
      <%# end %>
      <div class='pull-right'>
        <% if current_user %>
          <%= form_tag export_pcr_forms_path, :method => :get, :id => :pcr_form_form, :format => "xls" do %>
            <div class="controls">
              <input data-provide="datepicker" name="fromDate" id="fromDate" class="datepicker" placeholder="From Date">
              &nbsp;&nbsp;&nbsp;&nbsp;
              <input data-provide="datepicker" name="toDate" id="toDate" class="datepicker" placeholder="To Date">
              <input type="hidden" id="formatFile" name="format">
              &nbsp;&nbsp;&nbsp;&nbsp;
              <button id="exportCsv" class="btn btn-small">Export csv</button>
              <button id="exportXls"  class="btn btn-small">Export xls</button>
            </div>
          <% end -%>
        <% end -%>
      </div>
      <br>
      <br>
      <div>
        <h5>Total Record : <span class="badge"><%= "#{@currentRecord}/#{@totalRecord}"  %></span></h5>
        <h5>K13 Positive : <span class="badge"><%= @k13PositiveCase %></span></h5>
      </div>
      <br>
      <br>

<%= form_tag '', :method => :get do %>
  <div class="input-group col-sm-3">
    <%= text_field_tag :sample_id, params[:sample_id], class: "form-control",
                       placeholder: "Sample-ID", data: {url: pcr_forms_path} %>
    <br/>
    <br/>
    <%= select_tag 'k13', options_for_select(["All", "C580Y", "F583L*", "I543T", "NA", "NI", "PCR negative", "R539T", "WT", "Y493H", "Y616Y*"], params[:k13]), class: "form-control" %>
    <br/>
    <br/>
    <%= submit_tag 'search', class: 'btn btn-primary'%>
  </div>
<% end %>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>Sample-ID</th>
            <th>DBS_Received Date</th>
            <th>Date of case received</th>
            <th>PCR Screening</th>
            <th>Ct</th>
            <th>PCR Species</th>
            <th>Pre-K13 Result</th>
            <th>Final K13 Result</th>
            <th>Date of Pre-K13 Result</th>
            <th>Date of Final K13 Result</th>
            <th>Date of RDT </th>
            <th>Client Name</th>
            <th>Sex</th>
            <th>Age</th>
            <th>Phone number</th>
            <th>Village</th>
            <th>Commune</th>
            <th>Health Center</th>
            <th>Operational Disctrict</th>
            <th>Province</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <% #if current_user %>
            <th></th>
            <th></th>
            <% #end -%>
          </tr>
        </thead>

        <tbody>
        <% @pcrForms.each do |report| %>
          <tr>
            <td><%= report.sample_id %></td>
            <td><%= report.dbs_received_date.to_date if !report.dbs_received_date.nil? %></td>
            <td><%= report.date_of_case_received.to_date if !report.date_of_case_received.nil? %></td>
            <td><%= report.pcr_malaria %></td>
            <td><%= report.tm %></td>
            <td><%= report.rt_pcr_species %></td>
            <td><%= report.k13 %></td>
            <td><%= report.final_k13_result %></td>
            <td><%= report.date_of_k13_result.to_date if !report.date_of_k13_result.nil? %></td>
            <td><%= report.date_final_k13_result.to_date if !report.date_final_k13_result.nil? %></td>
            <td><%= report.date.to_date if !report.date.nil? %></td>
            <td><%= report.client_name %></td>
            <td><%= report.sex %></td>
            <td><%= report.age %></td>
            <td><%= report.phone_number %></td>
            <td><%= report.village %></td>
            <td><%= report.commune %></td>
            <td><%= report.hc %></td>
            <td><%= report.od %></td>
            <td><%= report.province %></td>
            <td><%= report.latitude %></td>
            <td><%= report.longitude %></td>
            <% if can? :edit, report %>
            <td><%= link_to 'Edit', edit_pcr_form_path(report, page: params[:page]) %></td>
            <td>
              <% if current_user.input_type == "" or current_user.input_type == nil %>
                <%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end -%>
              </td>
            <% end -%>
          </tr>
        <% end -%>
          <tr>
            <td colspan="23"><%= will_paginate @pcrForms %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="map" style="display:none;">
      <h5>Red Indicator : <span class="badge" style="background-color:#fd7567"><%= @redIndicator  %></span></h5>
      <h5>Blue Indicator : <span class="badge" style="background-color:#001dff"><%= @blueIndicator %></span></h5>
      <h5>Green Indicator : <span class="badge" style="background-color:#00e64d"><%= @greenIndicator %></span></h5>
      <div id="map-canvas" style="width: 100%; height: 800px; "></div>
    </div>
  </div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDY44OFIpEX_VvohK8q4iAhs8Vctkzv4V4&callback=initialize"></script>

 <script src="/assets/map.js" type"text/javascript"> </script>

app/views/pcr_forms/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    New PCR Survey
  </div>
  <div class="panel-body">
	<%= render 'form' %>
  </div>
</div>