config/routes.rb
Rails.application.routes.draw do

  get "questions/last" => "questions#last_question", :as => "questions/last"
  resources :import do
    collection do
      post :import
    end
  end
  resources :questions
  resources :reports do
    collection do
      get :export
    end
  end

  resources :jobs

  resources :diseases

  resources :users
  resources :pcr_forms do
    collection do
      get :export
      get :markers
    end
  end

  resources :locations do
    collection do
      get 'sub_locations'
      get 'all_provinces'
      get 'parent_locations_with_kind'
      get 'parent_location_with_child_id'
    end
  end

  root 'sessions#new'
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  resource :sessions

end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :locations, :foreign_key => 'province_id', :class_name => "Report", :dependent => :destroy
  has_many :locations, :foreign_key => 'district_id', :class_name => "Report", :dependent => :destroy
  has_many :locations, :foreign_key => 'commune_id', :class_name => "Report", :dependent => :destroy
	has_many :locations, :foreign_key => 'village_id', :class_name => "Report", :dependent => :destroy
	belongs_to :parent, :class_name => "Location"
  has_many :users

	validates :name, :kind, :presence => true


  def self.sub_location location
    locations = Location.where(:parent_id => location.id)
    if locations.length > 0
      children = []
      locations.each do |l|
        children = children + sub_location(l)
      end
      return [location] + children
    else
      return [location]
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  load_and_authorize_resource :except => [:create, :update], param_method: :location_params
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  skip_before_filter :check_authentication, :only => [:index, :parent_locations_with_kind, :parent_location_with_child_id, :sub_locations, :all_provinces]
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.order(:name)
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    if location_params[:kind] == 'Province'
      parent_id = nil
    elsif location_params[:kind] == 'District'
      parent_id = location_params[:province]
    elsif location_params[:kind] == 'Commune'
      parent_id = location_params[:district]
    else
      parent_id = location_params[:commune]
    end

    @location = Location.new(name: location_params[:name], kind: location_params[:kind], parent_id: parent_id)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    if location_params[:kind] == 'Province'
      parent_id = nil
    elsif location_params[:kind] == 'District'
      parent_id = location_params[:province]
    elsif location_params[:kind] == 'Commune'
      parent_id = location_params[:district]
    else
      parent_id = location_params[:commune]
    end 

    respond_to do |format|
      if @location.update(name: location_params[:name], kind: location_params[:kind], parent_id: parent_id)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def parent_locations_with_kind
    kind = params[:kind]
    location_id = params[:location_id]

    # p kind
    @location = Location.new
    if kind == 'District'
      locations = Location.where(:kind => 'Province')
    elsif kind == 'Commune'
      locations = Location.where(:kind => 'District')
    else
      locations = nil
    end
      
    respond_to do |format|
      format.json { render json: locations }
    end

  end

  def parent_location_with_child_id
    location_id = params[:location_id]

    # p kind
    @location = Location.new
    location = Location.find(location_id).parent
      
    respond_to do |format|
      format.json { render json: location }
    end

  end



  def sub_locations
    location_id = params[:location_id]
    locations =  Location.where(:parent_id => location_id)
    respond_to do |format|
      format.json {render json: locations}
    end
  end

  def all_provinces
    locations = Location.where(:kind => 'Province')
    respond_to do |format|
      format.json {render json: locations}
    end    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :province, :district, :kind, :commune)
    end
    def location_scope
      Location.order(:name)
    end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location, :html => { :class => 'form-horizontal ' }) do |f| %>
  <% if @location.errors.any? %>
    <div class="alert alert-error">
      <p><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</p>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name %>
    <div class='controls'>
      <%= f.text_field 'name' %><span class="text-error">*</span>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'Kind' %>
    <div class='controls'>
      <%= f.select('kind', [['Province', 'Province'], ['District', 'District'], ['Commune', 'Commune'], ['Village', 'Village']], include_blank: "select kind") %><span class="text-error">*</span>
    </div>
  </div>  



  <div class="control-group"​ id="province">
    <%= f.label 'Parent Province' %>
    <div class='controls'>
      <select name="location[province]" id="sel_province"></select>
    </div>
  </div>  

  <div class="control-group"​ id="district">
    <%= f.label 'Parent District' %>
    <div class='controls'>
      <select name="location[district]" id="sel_district"></select>
    </div>
  </div>  

  <div class="control-group"​ id="commune">
    <%= f.label 'Parent Commune' %>
    <div class='controls'>
      <select name="location[commune]" id="sel_commune"></select>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit 'Submit', :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

<script>
$(document).ready(function(){
  
  $('#location_kind').on('change',function(){
    kind = $('#location_kind').val();
    if(kind != ''){ 
      if(kind == 'Province'){
        $('#province').hide();
        $('#district').hide();
        $('#commune').hide();
      }else{
        get_all_provinces();
      }
    }
    // select_province();
  });

  $('#sel_province').on('change', function(){
    select_province();
  });

  $('#sel_district').on('change', function(){
    select_district();
  });
  
});

function select_province(){
  kind = $('#location_kind').val(); 
  if(kind != ''){
    if(kind == 'Commune'){
      $('#district').show();
      province_id = $('#sel_province').val();
      if(province_id != ''){
        get_sub_district(province_id);  
      }   
    }else if(kind == 'Village'){
      $('#district').show();
      province_id = $('#sel_province').val();
      if(province_id != ''){
        get_sub_district(province_id);  
      }


    }else{
      $('#district').hide();
    }
  }
}

function select_district(){
  kind = $('#location_kind').val(); 
  if(kind == 'Village'){
    $('#commune').show();
    district_id = $('#sel_district').val();
    if(district_id != ''){
      get_sub_commune(district_id);
    }
  }
}

function get_all_provinces(){
  $('#province').show();
  $('#district').hide();
  $('#sel_province').empty();
    $.ajax({
        type: "GET",
        url:'/locations/all_provinces.json', 
        success: function(response){
          $('#sel_province').append("<option>select province</option>");
          $.each( response, function( key, data ) {
            $('#sel_province').append("<option value='"+ data.id+"'>"+data.name+"</option>");    
          });
        }
    }); 
}

function get_sub_district(province_id){
  $('#sel_district').empty();
    $.ajax({
        type: "GET",
        url:'/locations/sub_locations.json', 
        data: {location_id: province_id},
        success: function(response){
          $('#sel_district').append("<option>select district</option>");
          $.each( response, function( key, data ) {
            $('#sel_district').append("<option value='"+ data.id+"'>"+data.name+"</option>");    
          });
        }
    });   
}

function get_sub_commune(district_id){
  $('#sel_commune').empty();
    $.ajax({
        type: "GET",
        url:'/locations/sub_locations.json', 
        data: {location_id: district_id},
        success: function(response){
          $('#sel_commune').append("<option>select commune</option>");
          $.each( response, function( key, data ) {
            $('#sel_commune').append("<option value='"+ data.id+"'>"+data.name+"</option>");    
          });
        }
    });   
}

</script>

app/views/locations/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Editing location
  </div>
  <div class="panel-body">
<%= form_for(@location, :html => { :class => 'form-horizontal ' }) do |f| %>
  <% if @location.errors.any? %>
    <div class="alert alert-error">
      <p><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</p>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name %>
    <div class='controls'>
      <%= f.text_field 'name' %><span class="text-error">*</span>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'Kind' %>
    <div class='controls'>
      <%= f.select('kind', [['Province', 'Province'], ['District', 'District'], ['Commune', 'Commune'], ['Village', 'Village']], include_blank: "select kind") %><span class="text-error">*</span>
    </div>
  </div>  



  <div class="control-group"​ id="edit_province">
    <%= f.label 'Parent Province' %>
    <div class='controls'>
      <%= f.hidden_field :parent_id %>
      <select name="location[province]" id="sel_province"></select>
    </div>
  </div>  

  <div class="control-group"​ id="edit_district">
    <%= f.label 'Parent District' %>
    <div class='controls'>
      <select name="location[district]" id="sel_district"></select>
    </div>
  </div>  

  <div class="control-group"​ id="edit_commune">
    <%= f.label 'Parent Commune' %>
    <div class='controls'>
      <select name="location[commune]" id="sel_commune"></select>
    </div>
  </div> 

  <div class="control-group">
    <div class="controls">
      <%= f.submit 'Submit', :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>
  </div>
</div>

<script>
$(document).ready(function(){
  kind = $('#location_kind').val();
  parent_id = $('#location_parent_id').val();

  if(kind == 'District'){
    get_all_provinces(parent_id);
  }

  if(kind == 'Commune'){
    get_province_by_district_id(parent_id);
  }
  
  if(kind == 'Village'){
    get_province_by_commune_id(parent_id);
  }


});

function get_province_by_commune_id(commune_id){
    $.ajax({
        type: "GET",
        url:'/locations/parent_location_with_child_id.json', 
        data: {location_id: commune_id},
        success: function(response){
          get_all_provinces(response['parent_id']);          
          get_sub_district(response['parent_id'], response['id']);
          get_sub_commune(response['id'], commune_id);
          $('#edit_province').show();
      $('#edit_district').show();
        }
    }); 
}

function get_province_by_district_id(district_id){
    $.ajax({
        type: "GET",
        url:'/locations/parent_location_with_child_id.json', 
        data: {location_id: district_id},
        success: function(response){    
          get_all_provinces(response['id']);          
          get_sub_district(response['id'], district_id);
          $('#edit_province').show();
      $('#edit_district').show();
        }
    }); 
}

function get_sub_district(province_id, selected_id){
  $('#sel_district').empty();
    $.ajax({
        type: "GET",
        url:'/locations/sub_locations', 
        data: {location_id: province_id},
        success: function(response){
          $('#sel_district').append("<option>select district</option>");
          $.each( response, function( key, data ) {
            $('#sel_district').append("<option value='"+ data.id+"'>"+data.name+"</option>");    
          });
          $('#sel_district').val(selected_id).attr('selected','selected');
        }
    });   
}

function get_sub_commune(district_id, selected_id){
  $('#sel_commune').empty();
    $.ajax({
        type: "GET",
        url:'/locations/sub_locations', 
        data: {location_id: district_id},
        success: function(response){
          $('#sel_commune').append("<option>select commune</option>");
          $.each( response, function( key, data ) {
            $('#sel_commune').append("<option value='"+ data.id+"'>"+data.name+"</option>");    
          });
          $('#sel_commune').val(selected_id).attr('selected','selected');
        }
    });   
}

function get_all_provinces(selected_id){
  $('#edit_province').show();
  $('#edit_district').hide();
  $('#sel_province').empty();
    $.ajax({
        type: "GET",
        url:'/locations/all_provinces.json',
        success: function(response){
          $('#sel_province').append("<option>select province</option>");
          $.each( response, function( key, data ) {
            $('#sel_province').append("<option value='"+ data.id+"'>"+data.name+"</option>");    
          });
          $('#sel_province').val(selected_id).attr('selected','selected');
        }
    }); 
}

</script>

app/views/locations/index.html.erb
<% if flash[:alert] %>
  <div class="alert alert-error">
  <%= flash[:alert] %>
  </div>
<% end -%>
<div class="panel panel-default">
  <div class="panel-heading">
    Listing location
  </div>
  <div class="panel-body">
    <% if can? :create, Location.new %>
    <%= link_to 'New location', new_location_path, :class => 'btn btn-small' %>
    <br/>
    <br/>
    <% end -%>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Kind</th>
          <th>Parent</th>
          <th></th>
          <% if current_user %>
          <th></th>
          <th></th>
          <% end -%>
        </tr>
      </thead>

      <tbody>
        <% i = 0 %>
        <% @locations.each do |location| %>
          <tr>
            <td><%= i=i+1 %></td>
            <td><%= location.name %></td>
            <td><%= location.kind %></td>
            <td><%= location.parent.name if !location.parent.nil? %></td>
            <td><%= link_to 'Show', location %></td>
            <% if can? :manage, location %>
            <td><%= link_to 'Edit', edit_location_path(location) %></td>
            <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end -%>
          </tr>
        <% end %>       
      </tbody>
    </table>
  </div>
</div>

app/views/locations/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    New location
  </div>
  <div class="panel-body">
	<%= render 'form' %>
  </div>
</div>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
<strong>Kind:</strong>
  <%= @location.kind %>
</p>

<p>
<strong>Parent:</strong>
  <%= @location.parent.name if !@location.parent.nil? %>
</p>
<% if can? :update, @location %>
<%= link_to 'Edit', edit_location_path(@location) %> |
<% end -%>
<%= link_to 'Back', locations_path %>