config/routes.rb
Rails.application.routes.draw do

  get "questions/last" => "questions#last_question", :as => "questions/last"
  resources :import do
    collection do
      post :import
    end
  end
  resources :questions
  resources :reports do
    collection do
      get :export
    end
  end

  resources :jobs

  resources :diseases

  resources :users
  resources :pcr_forms do
    collection do
      get :export
      get :markers
    end
  end

  resources :locations do
    collection do
      get 'sub_locations'
      get 'all_provinces'
      get 'parent_locations_with_kind'
      get 'parent_location_with_child_id'
    end
  end

  root 'sessions#new'
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  resource :sessions

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Malaria Case Transfer" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <a href="#" class="brand">Malaria Case Transfer</a>


          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <% if admin_user %>
                <li><%= link_to "Report", reports_path %></li>
                <li><%= link_to "PCR Form", pcr_forms_path  %></li>
                <li><%= link_to "User", users_path %></li>
                <li><%= link_to "Disease", diseases_path  %></li>
                <li><%= link_to "Location", locations_path  %></li>
                <li><%= link_to "Question", questions_path  %></li>
              <% elsif pfd_data_entry_user %>
                <li><%= link_to "PCR Form", new_pcr_form_path  %></li>
              <% elsif pfd_user %>
                <li><%= link_to "PCR Form", pcr_forms_path  %></li>
              <% elsif report_master_user %>
                <li><%= link_to "Report", reports_path %></li>
                <li><%= link_to "Disease", diseases_path  %></li>
                <li><%= link_to "Location", locations_path  %></li>
              <% elsif report_viewer_user %>
                <li><%= link_to "Report", reports_path %></li>
              <% end -%>
            </ul>

            <% if current_user %>
            <ul class="nav pull-right">
              <li><%= link_to "Log out (#{current_user.username})", logout_path  %></li>
            </ul>
          <% else %>
            <ul class="nav pull-right">
              <li><%= link_to "Log in", login_path  %></li>
            </ul>
          <% end -%>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">

          <%= yield %>

      </div><!--/row-->

      </div>

    </div> <!-- /container -->

  </body>
  <!-- <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDY44OFIpEX_VvohK8q4iAhs8Vctkzv4V4&callback=initialize">
  </script> -->
</html>